version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "bridge/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: cd bridge && npm ci
      - save_cache:
          paths:
            - bridge/node_modules
          key: v1-dependencies-{{ checksum "bridge/package.json" }}
      - run: cd bridge && npm run lint